# frozen_string_literal: true

class CreateAuctifySales < ActiveRecord::Migration[6.0]
  # rubocop:disable Layout/LineLength
  # cool! Generated by `bin/rails generate scaffold sale seller:references{polymorphic}, buyer:references{polymorphic}, item:references{polymorphic}`
  # rubocop:enable Layout/LineLength
  def change
    create_table :auctify_sales do |t|
      t.references :seller, polymorphic: true, null: false
      t.references :buyer, polymorphic: true, null: true
      t.references :item, polymorphic: true, null: false

      t.timestamps
    end
  end
end
